-- MySQL Script generated by MySQL Workbench
-- Fri Oct 15 23:28:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biocad_rds
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biocad_rds` ;

-- -----------------------------------------------------
-- Schema biocad_rds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biocad_rds` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `biocad_rds` ;

-- -----------------------------------------------------
-- Table `accept_file_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accept_file_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `accept_file_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_id` INT NOT NULL,
  `content_type` INT NOT NULL,
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `accept_file_type` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `analysis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analysis` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `analysis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app` INT NOT NULL,
  `main_file` INT NOT NULL COMMENT '如果分析只需要一个文件，那么就使用这个属性来储存',
  `files` TINYTEXT NOT NULL COMMENT '分析文件的id编号的数组的json字符串',
  `project` INT NOT NULL,
  `user_id` INT NOT NULL,
  `parameters` LONGTEXT NOT NULL COMMENT '分析用的参数json',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `analysis` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `analysis_app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analysis_app` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `analysis_app` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` MEDIUMTEXT NOT NULL,
  `project_type` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `version` VARCHAR(32) NOT NULL DEFAULT '1.0.0.0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `analysis_app` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `content_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `content_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `content_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `suffix` VARCHAR(16) NOT NULL,
  `content_type` VARCHAR(128) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `class` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `content_types` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `data_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_files` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `data_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT '这个文件拥有者的用户表编号',
  `name` VARCHAR(128) NOT NULL COMMENT '从浏览器端得到的原始文件名',
  `suffix` VARCHAR(16) NOT NULL,
  `content_type` INT NOT NULL,
  `uri` VARCHAR(256) NOT NULL COMMENT '文件在服务器上面的真实路径，为了保护用户数据，用户所上传的数据文件的文件名都是经过随机唯一编码的，所以会需要使用这个字段来记录文件的真实路径',
  `size` INT NOT NULL,
  `upload_time` DATETIME NOT NULL,
  `md5` VARCHAR(32) NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '共享文件池';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `data_files` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `file_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file_class` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `file_class` (
  `classId` INT NOT NULL COMMENT '枚举值',
  `bioClassType` VARCHAR(32) NOT NULL COMMENT '图标类型，枚举的成员',
  PRIMARY KEY (`classId`))
ENGINE = InnoDB
COMMENT = '在这个表之中的设计决定了文件的mime type在UI上面的显示图标，这是一个typescript之中的枚举值';

SHOW WARNINGS;
CREATE UNIQUE INDEX `classId_UNIQUE` ON `file_class` (`classId` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `create_time` DATETIME NULL,
  `read` INT NOT NULL DEFAULT 0,
  `type` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `messages` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(64) NULL,
  `description` TINYTEXT NULL,
  `type` INT NOT NULL DEFAULT -1,
  `workspace` VARCHAR(256) NOT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `project` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_files` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  `join_time` DATETIME NOT NULL COMMENT '将用户的项目和文件这两个实体之间建立起关联的时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '分析项目和文件池之中的文件的关联关系';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `project_files` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `note` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `project_types` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `report` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `analysis_list` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `report` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sha1` VARCHAR(32) NOT NULL COMMENT '对id的md5哈希值',
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `app_id` INT NOT NULL COMMENT '这个任务所使用到的分析程序的编号，后台任务系统会需要这个编号来调用相应的数据分析程序',
  `title` VARCHAR(128) NOT NULL,
  `create_time` DATETIME NOT NULL,
  `finish_time` DATETIME NULL,
  `status` INT NOT NULL COMMENT '任务状态或者任务的执行结果\n\n0: 任务等待被执行\n1: 任务执行中\n200: 执行成功\n500: 出错',
  `note` TINYTEXT NULL,
  `parameters` LONGTEXT NOT NULL COMMENT '参数json',
  PRIMARY KEY (`id`, `sha1`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `task` (`id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `sha1_UNIQUE` ON `task` (`sha1` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(32) NOT NULL COMMENT 'lower(md5)',
  `role` INT NOT NULL DEFAULT 0 COMMENT '用户在这个网站上面的角色类型\n\n0 - normal user\n1 - admin',
  `status` INT NOT NULL COMMENT '用户的状态：\n\n0 - Email account not actived\n200 - user actived\n403 - user banned',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户的基本信息表';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `user` (`id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `account_UNIQUE` ON `user` (`account` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `user` (`email` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_activity` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  `api` VARCHAR(128) NOT NULL COMMENT 'web api',
  `method` VARCHAR(16) NOT NULL COMMENT 'GET/POST/PUT/DELETE, etc',
  `status_code` INT NOT NULL DEFAULT 200 COMMENT '200: api call success\n500: api call throw exception\n403: access denied\n404: app not found',
  `time` DATETIME NOT NULL,
  `exception` LONGTEXT NULL,
  `expression` LONGTEXT NULL,
  `stack_trace` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用于统计分析用户的使用习惯，安全性检测以及程序错误信息的记录表';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `user_activity` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_settings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_settings` (
  `user_id` INT NOT NULL,
  `email_notify.login` INT NOT NULL DEFAULT 1,
  `email_notify.security` INT NOT NULL DEFAULT 1,
  `email_notify.task.start` INT NOT NULL DEFAULT 1,
  `email_notify.task.success` INT NOT NULL DEFAULT 1,
  `email_notify.task.error` INT NOT NULL DEFAULT 1,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
COMMENT = '1: boolean TRUE\n0: boolean FALSE';

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_id_UNIQUE` ON `user_settings` (`user_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
