-- MySQL Script generated by MySQL Workbench
-- Mon Jun 18 04:24:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bioCAD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bioCAD` ;

-- -----------------------------------------------------
-- Schema bioCAD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bioCAD` DEFAULT CHARACTER SET utf8 ;
USE `bioCAD` ;

-- -----------------------------------------------------
-- Table `bioCAD`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`user` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(32) NOT NULL COMMENT 'lower(md5)',
  `role` INT NOT NULL DEFAULT 0 COMMENT '用户在这个网站上面的角色类型',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
COMMENT = '用户的基本信息表';


-- -----------------------------------------------------
-- Table `bioCAD`.`user_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`user_settings` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`user_settings` (
  `user_id` INT NOT NULL,
  `email_notify.login` INT NOT NULL DEFAULT 1,
  `email_notify.security` INT NOT NULL DEFAULT 1,
  `email_notify.task.start` INT NOT NULL DEFAULT 1,
  `email_notify.task.success` INT NOT NULL DEFAULT 1,
  `email_notify.task.error` INT NOT NULL DEFAULT 1,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB
COMMENT = '1: boolean TRUE\n0: boolean FALSE';


-- -----------------------------------------------------
-- Table `bioCAD`.`project_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`project_types` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`project_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `note` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bioCAD`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`project` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(64) NULL,
  `description` TINYTEXT NULL,
  `type` INT NOT NULL DEFAULT -1,
  `workspace` VARCHAR(256) NOT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bioCAD`.`user_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`user_activity` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`user_activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  `api` VARCHAR(128) NOT NULL COMMENT 'web api',
  `method` VARCHAR(16) NOT NULL COMMENT 'GET/POST/PUT/DELETE, etc',
  `status_code` INT NOT NULL DEFAULT 200 COMMENT '200: api call success\n500: api call throw exception\n403: access denied\n404: app not found',
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '用于统计分析用户的使用习惯，安全性检测以及程序错误信息的记录表';


-- -----------------------------------------------------
-- Table `bioCAD`.`exception`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`exception` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`exception` (
  `id` INT NOT NULL COMMENT '(user_activity id for code 500) 当在用户活动表之中出现500错误的时候，所记录下的对应的用于程序调试的错误信息，这个id是对应的用户活动表的记录id',
  `expression` LONGTEXT NOT NULL COMMENT '产生这个错误所需要的表达式，包括：\n\n+ SQL查询语句\n+ 命令行命令',
  `stack_trace` LONGTEXT NOT NULL COMMENT '堆栈追踪信息',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '程序的错误信息表';


-- -----------------------------------------------------
-- Table `bioCAD`.`analysis_app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`analysis_app` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`analysis_app` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` MEDIUMTEXT NOT NULL,
  `project_type` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `version` VARCHAR(32) NOT NULL DEFAULT '1.0.0.0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bioCAD`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`task` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sha1` VARCHAR(32) NOT NULL,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `app_id` INT NOT NULL COMMENT '这个任务所使用到的分析程序的编号，后台任务系统会需要这个编号来调用相应的数据分析程序',
  `title` VARCHAR(128) NOT NULL,
  `create_time` DATETIME NOT NULL,
  `finish_time` DATETIME NULL,
  `status` INT NOT NULL COMMENT '任务状态或者任务的执行结果\n\n0: 任务等待被执行\n1: 任务执行中\n200: 执行成功\n500: 出错',
  `note` TINYTEXT NULL,
  `parameters` LONGTEXT NOT NULL COMMENT '参数json',
  PRIMARY KEY (`id`, `sha1`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `sha1_UNIQUE` (`sha1` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bioCAD`.`content_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`content_types` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`content_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `suffix` VARCHAR(16) NOT NULL,
  `content_type` VARCHAR(128) NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bioCAD`.`data_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`data_files` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`data_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT '这个文件拥有者的用户表编号',
  `name` VARCHAR(128) NOT NULL COMMENT '从浏览器端得到的原始文件名',
  `suffix` VARCHAR(16) NOT NULL,
  `content_type` INT NOT NULL,
  `uri` VARCHAR(256) NOT NULL COMMENT '文件在服务器上面的真实路径，为了保护用户数据，用户所上传的数据文件的文件名都是经过随机唯一编码的，所以会需要使用这个字段来记录文件的真实路径',
  `size` INT NOT NULL,
  `upload_time` DATETIME NOT NULL,
  `md5` VARCHAR(32) NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '共享文件池';


-- -----------------------------------------------------
-- Table `bioCAD`.`analysis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`analysis` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`analysis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app` INT NOT NULL,
  `main_file` INT NOT NULL COMMENT '如果分析只需要一个文件，那么就使用这个属性来储存',
  `files` TINYTEXT NOT NULL COMMENT '分析文件的id编号的数组的json字符串',
  `project` INT NOT NULL,
  `user_id` INT NOT NULL,
  `parameters` LONGTEXT NOT NULL COMMENT '分析用的参数json',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bioCAD`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`report` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `analysis_list` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bioCAD`.`project_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`project_files` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`project_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  `join_time` DATETIME NOT NULL COMMENT '将用户的项目和文件这两个实体之间建立起关联的时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '分析项目和文件池之中的文件的关联关系';


-- -----------------------------------------------------
-- Table `bioCAD`.`accept_file_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`accept_file_type` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`accept_file_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_id` INT NOT NULL,
  `content_type` INT NOT NULL,
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
