-- MySQL Script generated by MySQL Workbench
-- Sun Apr  1 19:23:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bioCAD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bioCAD` ;

-- -----------------------------------------------------
-- Schema bioCAD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bioCAD` DEFAULT CHARACTER SET utf8 ;
USE `bioCAD` ;

-- -----------------------------------------------------
-- Table `bioCAD`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`user` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `role` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bioCAD`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`settings` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`settings` (
  `user_id` INT NOT NULL,
  `settingscol` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bioCAD`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bioCAD`.`project` ;

CREATE TABLE IF NOT EXISTS `bioCAD`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(64) NULL,
  `description` TINYTEXT NULL,
  `type` INT NOT NULL DEFAULT -1,
  `workspace` VARCHAR(256) NOT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
